language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo

jobs:
  include:
    - stage: build-latest-image
      branches:
        only:
          - master
      script:
        - docker build -t kilerd/rubble:latest .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push kilerd/rubble:latest